<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan Data Booking</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { text-align: center; margin-top: 20px; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Laporan Data Booking</h2>
        <p>Tanggal Cetak: {{ date('d/m/Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nama User</th>
                <th>Layanan</th>
                <th>Lokasi</th>
                <th>Tanggal Booking</th>
                <th>Status</th>
                <th>Harga</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $request)
            <tr>
                <td>{{ $request->id_request }}</td>
                <td>{{ $request->user->name ?? '-' }}</td>
                <td>{{ $request->layanan }}</td>
                <td>{{ $request->lokasi }}</td>
                <td>{{ \Carbon\Carbon::parse($request->tanggal_booking)->format('d/m/Y') }}</td>
                <td>{{ $request->status_admin }}</td>
                <td>Rp{{ number_format($request->jumlah_pembayaran, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
    </div>
</body>
</html>